### ISSUE TITLE
Idle inhibitor icon - waybar

### ISSUE THREAD

**Issue by 4Bravo** [Reyshyram/Dotfiles#13]
How to get rid of the "sleep when idle" icon in the top right corner? I tried just commenting the `"idle_inhibitor",` in `.config/waybar`, that makes it disappear and cuts the custom/wlogout icon instead of making in rounded. I also tried messing with the .css but it didn't do much

**Comment by Reyshyram** [comment]
Inside of the style.css file, you need to adjust the css in order to make the wlogout icon rounded. It's around here :

```css
#custom-wlogout {
    font-size: 16px;
    margin-right: 0px;
    margin-left: 0px;
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
    padding-left: 8px;
}
```

Just remove margin-left and the lines related to the border radius
